# 指定基础镜像
FROM alpine


# 添加时区处理
RUN echo -e "https://mirrors.aliyun.com/alpine/v3.21/main\nhttps://mirrors.aliyun.com/alpine/v3.21/community" > /etc/apk/repositories && \
    apk update &&\
    apk --no-cache add tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" >  /etc/timezone

ENV TZ=Asia/Shanghai

# 定义 Dockfile 中的变量
ARG SERVER_NAME=user
ARG SERVER_TYPE=rpc

# 指定运行运行脚本文件
ENV RUN_BIN bin/${SERVER_NAME}-${SERVER_TYPE}
# 指定配置文件
ENV RUN_CONF /${SERVER_NAME}/conf/${SERVER_NAME}.yaml

RUN mkdir /$SERVER_NAME && mkdir /$SERVER_NAME/bin && mkdir /$SERVER_NAME/conf

# 复制编译之后的二进制文件
COPY ./bin/$SERVER_NAME-$SERVER_TYPE /$SERVER_NAME/bin/

# 复制配置文件
COPY ./apps/$SERVER_NAME/$SERVER_TYPE/etc/dev/$SERVER_NAME.yaml /$SERVER_NAME/conf

# 为二进制文件提供执行权限
RUN chmod +x /$SERVER_NAME/bin/$SERVER_NAME-$SERVER_TYPE

WORKDIR /$SERVER_NAME

ENTRYPOINT $RUN_BIN -f $RUN_CONF